[project]
name = "modulelearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.1.0",
    "textual>=5.0.1",
    "typer>=0.16.0",
]
